interface actionDraftInterface {
  data?: object;
  loading: boolean;
  success: boolean;
  error: boolean;
  errorType?: string | null;
}

export const types = {
  FETCHING_USER_TYPES: 'FETCHING_USER_TYPES',
  USER_TYPES_FETCH_SUCCESSFULLY: 'USER_TYPES_FETCH_SUCCESSFULLY',
  FAILURE_FETCH_USER_TYPES: 'FAILURE_FETCH_USER_TYPES',

  FETCHING_USER_DATA: 'FETCHING_USER_DATA',
  USER_DATA_FETCH_SUCCESSFULLY: 'USER_DATA_FETCH_SUCCESSFULLY',
  FAILURE_FETCH_USER_DATA: 'FAILURE_FETCH_USER_DATA',

  FETCHING_INTERNAL_USER_DATA: 'FETCHING_INTERNAL_USER_DATA',
  INTERNAL_USER_DATA_FETCH_SUCCESSFULLY: 'INTERNAL_USER_DATA_FETCH_SUCCESSFULLY',
  FAILURE_FETCH_INTERNAL_USER_DATA: 'FAILURE_FETCH_INTERNAL_USER_DATA',

  FETCHING_VIACEP_ADDRESS_BY_ZIPCODE: 'FETCHING_VIACEP_ADDRESS_BY_ZIPCODE',
  VIACEP_ADDRESS_BY_ZIPCODE_FETCH_SUCCESSFULLY: 'VIACEP_ADDRESS_BY_ZIPCODE_FETCH_SUCCESSFULLY',
  FAILURE_FETCH_VIACEP_ADDRESS_BY_ZIPCODE: 'FAILURE_FETCH_VIACEP_ADDRESS_BY_ZIPCODE',

  FETCHING_STATES: 'FETCHING_STATES',
  STATES_FETCH_SUCCESSFULLY: 'STATES_FETCH_SUCCESSFULLY',
  FAILURE_FETCH_STATES: 'FAILURE_FETCH_STATES',

  FETCHING_CITIES_BY_STATE: 'FETCHIN_CITIES_BY_STATE',
  CITIES_BY_STATE_FETCH_SUCCESSFULLY: 'CITIES_BY_STATE_FETCH_SUCCESSFULLY',
  FAILURE_FETCH_CITIES_BY_STATE: 'FAILURE_FETCH_CITIES_BY_STATE',

  CREATING_COMPANY: 'CREATING_COMPANY',
  COMPANY_CREATED_SUCCESSFULLY: 'COMPANY_CREATED_SUCCESSFULLY',
  FAILURE_CREATE_COMPANY: 'FAILURE_CREATE_COMPANY',

  FETCHING_COMPANY_BY_CNPJ: 'FETCHING_COMPANY_BY_CNPJ',
  COMPANY_BY_CNPJ_FETCH_SUCCESSFULLY: 'COMPANY_BY_CNPJ_FETCH_SUCCESSFULLY',
  FAILURE_FETCH_COMPANY_BY_CNPJ: 'FAILURE_FETCH_COMPANY_BY_CNPJ',

  FETCHING_COMPANIES_NON_VALIDATED: 'FETCHING_ALL_COMPANIES_NON_VALIDATED',
  COMPANIES_NON_VALIDATED_FETCH_SUCCESSFULLY: 'COMPANIES_NON_VALIDATED_FETCH_SUCCESSFULLY',
  FAILURE_FETCH_COMPANIES_NON_VALIDATED: 'FAILURE_FETCH_COMPANIES_NON_VALIDATED',

  VALIDATING_COMPANY: 'VALIDATING_COMPANY',
  COMPANY_VALIDATED_SUCCESSFULLY: 'COMPANY_VALIDATED_SUCCESSFULLY',
  FAILURE_VALIDATE_COMPANY: 'FAILURE_VALIDATE_COMPANY',

  REFUSING_COMPANY: 'REFUSING_COMPANY',
  COMPANY_REFUSED_SUCCESSFULLY: 'COMPANY_REFUSED_SUCCESSFULLY',
  FAILURE_REFUSE_COMPANY: 'FAILURE_REFUSE_COMPANY',

  UPDATING_COMPANY: 'UPDATING_COMPANY',
  COMPANY_UPDATED_SUCCESSFULLY: 'COMPANY_UPDATED_SUCCESSFULLY',
  FAILURE_UPDATE_COMPANY: 'FAILURE_UPDATE_COMPANY',

  FETCHING_COMPANY_BY_ID: 'FETCHING_COMPANY_BY_ID',
  COMPANY_FETCHED_BY_ID_SUCCESSFULLY: 'COMPANY_FETCHED_BY_ID_SUCCESSFULLY',
  FAILURE_FETCH_COMPANY_BY_ID: 'FAILURE_FETCH_COMPANY_BY_ID',

  FETCHING_USER_BY_EMAIL: 'FETCHING_USER_BY_EMAIL',
  USER_BY_EMAIL_FETCH_SUCCESSFULLY: 'USER_BY_EMAIL_FETCH_SUCCESSFULLY',
  FAILURE_FETCH_USER_BY_EMAIL: 'FAILURE_FETCH_USER_BY_EMAIL',

  CLEARING_REDUX_AUTH_DATA: 'CLEARING_REDUX_AUTH_DATA',
  REDUX_AUTH_DATA_CLEARED_SUCCESSFULLY: 'REDUX_AUTH_DATA_CLEARED_SUCCESSFULLY',
  FAILURE_CLEAR_REDUX_AUTH_DATA: 'FAILURE_CLEAR_REDUX_AUTH_DATA',

  RECORDING_DATA_ON_THE_CHIP: 'RECORDING_DATA_ON_THE_CHIP',
  DATA_SUCCESSFULLY_RECORDED_ON_THE_CHIP: 'DATA_SUCCESSFULLY_RECORDED_ON_THE_CHIP',
  FAILURE_RECORD_DATA_ON_THE_CHIP: 'FAILURE_RECORD_DATA_ON_THE_CHIP',

  READING_DATA_FROM_CHIP: 'READING_DATA_FROM_CHIP',
  CHIP_DATA_READ_SUCCESSFULLY: 'CHIP_DATA_READ_SUCCESSFULLY',
  FAILURE_READ_DATA_FROM_CHIP: 'FAILURE_READ_DATA_FROM_CHIP',

  READING_OFFLINE_DATA_FROM_CHIP: 'READING_OFFLINE_DATA_FROM_CHIP',
  OFFLINE_CHIP_DATA_READ_SUCCESSFULLY: 'OFFLINE_CHIP_DATA_READ_SUCCESSFULLY',
  FAILURE_READ_OFFLINE_DATA_FROM_CHIP: 'FAILURE_READ_OFFLINE_DATA_FROM_CHIP',

  WRITING_GRAPHIC_DATA: 'WRITING_GRAPHIC_DATA',
  GRAPHIC_DATA_WRITED_SUCCESSFULLY: 'GRAPHIC_DATA_WRITED_SUCCESSFULLY',
  FAILURE_WRITE_GRAPHIC_DATA: 'FAILURE_WRITE_GRAPHIC_DATA',

  WRITING_WORKSHOP_DATA: 'WRITING_WORKSHOP_DATA',
  WORKSHOP_DATA_WRITED_SUCCESSFULLY: 'WORKSHOP_DATA_WRITED_SUCCESSFULLY',
  FAILURE_WRITE_WORKSHOP_DATA: 'FAILURE_WRITE_WORKSHOP_DATA',

  WRITING_FRENTIST_DATA: 'WRITING_FRENTIST_DATA',
  FRENTIST_DATA_WRITED_SUCCESSFULLY: 'FRENTIST_DATA_WRITED_SUCCESSFULLY',
  FAILURE_WRITE_FRENTIST_DATA: 'FAILURE_WRITE_FRENTIST_DATA',

  FETCHING_GRAPHIC_DATA: 'FETCHING_GRAPHIC_DATA',
  GRAPHIC_DATA_FETCHED_SUCCESSFULLY: 'GRAPHIC_DATA_FETCHED_SUCCESSFULLY',
  FAILURE_FETCH_GRAPHIC_DATA: 'FAILURE_FETCH_GRAPHIC_DATA',

  FETCHING_WORKSHOP_DATA: 'FETCHING_WORKSHOP_DATA',
  WORKSHOP_DATA_FETCHED_SUCCESSFULLY: 'WORKSHOP_DATA_FETCHED_SUCCESSFULLY',
  FAILURE_FETCH_WORKSHOP_DATA: 'FAILURE_FETCH_WORKSHOP_DATA',

  FETCHING_FRENTIST_DATA: 'FETCHING_FRENTIST_DATA',
  FRENTIST_DATA_FETCHED_SUCCESSFULLY: 'FRENTIST_DATA_FETCHED_SUCCESSFULLY',
  FAILURE_FETCH_FRENTIST_DATA: 'FAILURE_FETCH_FRENTIST_DATA',

  FETCHING_INSPECTOR_DATA: 'FETCHING_INSPECTOR_DATA',
  INSPECTOR_DATA_FETCHED_SUCCESSFULLY: 'INSPECTOR_DATA_FETCHED_SUCCESSFULLY',
  FAILURE_FETCH_INSPECTOR_DATA: 'FAILURE_FETCH_INSPECTOR_DATA',

  DECRYPTING_DATA_READING_FILLING_STATION: 'DECRYPTING_DATA_READING_FILLING_STATION',
  DATA_READING_FILLING_STATION_DECRYPTED_SUCCESSFULLY: 'DATA_READING_FILLING_STATION_DECRYPTED_SUCCESSFULLY',
  FAILURE_DECRYPT_DATA_READING_FILLING_STATION: 'FAILURE_DECRYPT_DATA_READING_FILLING_STATION',

  GENERATING_SPREADSHEET_VALIDATION_DATA_FILLING_STATION: 'GENERATING_SPREADSHEET_VALIDATION_DATA_FILLING_STATION',
  SPREADSHEET_VALIDATION_DATA_FILLING_STATION_GENERATE_SUCCESSFULLY:
    'SPREADSHEET_VALIDATION_DATA_FILLING_STATION_GENERATE_SUCCESSFULLY',
  FAILURE_GENERATE_SPREADSHEET_VALIDATION_DATA_FILLING_STATION:
    'FAILURE_GENERATE_SPREADSHEET_VALIDATION_DATA_FILLING_STATION',

  BLOCKING_CHIP: 'BLOCKING_CHIP',
  CHIP_SUCCESSFULLY_BLOCKED: 'CHIP_SUCCESSFULLY_BLOCKED',
  FAILURE_BLOCK_CHIP: 'FAILURE_BLOCK_CHIP',

  CHECKING_CONNECTION_CHIP: 'CHECKING_CONNECTION_CHIP',
  CHIP_SUCCESSFULLY_CONNECTION_CHECKED: 'CHIP_SUCCESSFULLY_CONNECTION_CHECKED',
  FAILURE_CHECK_CONNECTION_CHIP: 'FAILURE_CHECK_CONNECTION_CHIP',

  CHECKING_OFFLINE_CONNECTION_CHIP: 'CHECKING_OFFLINE_CONNECTION_CHIP',
  CHIP_SUCCESSFULLY_OFFLINE_CONNECTION_CHECKED: 'CHIP_SUCCESSFULLY_OFFLINE_CONNECTION_CHECKED',
  FAILURE_CHECK_OFFLINE_CONNECTION_CHIP: 'FAILURE_CHECK_OFFLINE_CONNECTION_CHIP',

  CHECKING_BLOCK_CHIP: 'CHECKING_BLOCK_CHIP',
  CHIP_SUCCESSFULLY_BLOCK_CHECKED: 'CHIP_SUCCESSFULLY_BLOCK_CHECKED',
  FAILURE_CHECK_BLOCK_CHIP: 'FAILURE_CHECK_BLOCK_CHIP',

  FETCHING_LOGS: 'FETCHING_LOGS',
  LOGS_FETCHED_SUCCESSFULLY: 'LOGS_FETCHED_SUCCESSFULLY',
  FAILURE_FETCH_LOGS: 'FAILURE_FETCH_LOGS',

  FINALLY_REQUEST_USER_TYPES: 'FINALLY_REQUEST_USER_TYPES',
  FINALLY_REQUEST_USER_DATA: 'FINALLY_REQUEST_USER_DATA',
  FINALLY_REQUEST_INTERNAL_USER_DATA: 'FINALLY_REQUEST_INTERNAL_USER_DATA',
  FINALLY_REQUEST_VIACEP_ADDRESS_BY_ZIPCODE: 'FINALLY_REQUEST_VIACEP_ADDRESS_BY_ZIPCODE',
  FINALLY_REQUEST_STATES: 'FINALLY_REQUEST_STATES',
  FINALLY_REQUEST_CITIES_BY_STATE: 'FINALLY_REQUEST_CITIES_BY_STATE',
  FINALLY_REQUEST_GRAPHIC_DATA: 'FINALLY_REQUEST_GRAPHIC_DATA',
  FINALLY_REQUEST_WORKSHOP_DATA: 'FINALLY_REQUEST_WORKSHOP_DATA',
  FINALLY_REQUEST_FRENTIST_DATA: 'FINALLY_REQUEST_FRENTIST_DATA',
  FINALLY_REQUEST_INSPECTOR_DATA: 'FINALLY_REQUEST_INSPECTOR_DATA',
  FINALLY_REQUEST_BLOCK_CHIP: 'FINALLY_REQUEST_BLOCK_CHIP',
  FINALLY_REQUEST_CHECK_CONNECTION_CHIP: 'FINALLY_REQUEST_CHECK_CONNECTION_CHIP',
  FINALLY_REQUEST_CHECK_OFFLINE_CONNECTION_CHIP: 'FINALLY_REQUEST_CHECK_OFFLINE_CONNECTION_CHIP',
  FINALLY_REQUEST_CHECK_BLOCK_CHIP: 'FINALLY_REQUEST_CHECK_BLOCK_CHIP',
  FINALLY_REQUEST_LOGS: 'FINALLY_REQUEST_LOGS',

  FINALLY_CREATE_COMPANY: 'FINALLY_CREATE_COMPANY',
  FINALLY_REQUEST_COMPANY_BY_CNPJ: 'FINALLY_REQUEST_COMPANY_BY_CNPJ',
  FINALLY_REQUEST_COMPANIES_NON_VALIDATED: 'FINALLY_REQUEST_COMPANIES_NON_VALIDATED',
  FINALLY_REQUEST_VALIDATE_COMPANY: 'FINALLY_REQUEST_VALIDATE_COMPANY',
  FINALLY_REQUEST_REFUSE_COMPANY: 'FINALLY_REQUEST_REFUSE_COMPANY',
  FINALLY_UPDATE_COMPANY: 'FINALLY_UPDATE_COMPANY',
  FINALLY_FETCH_COMPANY_BY_ID: 'FINALLY_FETCH_COMPANY_BY_ID',

  FINALLY_REQUEST_USER_BY_EMAIL: 'FINALLY_REQUEST_USER_BY_EMAIL',

  FINALLY_CLEAR_REDUX_AUTH_DATA: 'FINALLY_CLEAR_REDUX_AUTH_DATA',

  FINALLY_GENERATE_SPREADSHEET_VALIDATION_DATA_FILLING_STATION:
    'FINALLY_GENERATE_SPREADSHEET_VALIDATION_DATA_FILLING_STATION',
  FINALLY_DECRYPT_READING_DATA_FILLING_STATION: 'FINALLY_DECRYPT_READING_DATA_FILLING_STATION',

  FINALLY_RECORD_DATA_ON_THE_CHIP: 'FINALLY_RECORD_DATA_ON_THE_CHIP',
  FINALLY_READ_DATA_FROM_THE_CHIP: 'FINALLY_READ_DATA_FROM_THE_CHIP',
  FINALLY_READ_OFFLINE_DATA_FROM_THE_CHIP: 'FINALLY_READ_OFFLINE_DATA_FROM_THE_CHIP',

  SYSTEM: {
    RESTART: {
      REQUEST: 'SYSTEM/RESTART/REQUEST',
      SUCCESS: 'SYSTEM/RESTART/SUCCESS',
      FAILURE: 'SYSTEM/RESTART/FAILURE',
      FINALLY: 'SYSTEM/RESTART/FINALLY',
    },
  },

  INMETRO: {
    SERIAL: {
      TYPE: {
        REQUEST: 'INMETRO/SERIAL/TYPE/REQUEST',
        SUCCESS: 'INMETRO/SERIAL/TYPE/SUCCESS',
        FAILURE: 'INMETRO/SERIAL/TYPE/FAILURE',
        FINALLY: 'INMETRO/SERIAL/TYPE/FINALLY',
      },
    },
  },
};

export const loading = (draft: actionDraftInterface) => {
  draft.data = {};
  draft.loading = true;
  draft.success = false;
  draft.error = false;
  draft.errorType = null;
};

export const success = (draft: actionDraftInterface) => {
  draft.loading = false;
  draft.success = true;
  draft.error = false;
};

export const failure = (action: any, draft: actionDraftInterface) => {
  if (action.payload && Object.keys(action.payload.data).length) {
    draft.data = action.payload.data;

    if (action.payload.data.errorType) draft.errorType = action.payload.data.errorType;
  }

  draft.data = draft.data && Object.keys(draft.data).length ? draft.data : {};
  draft.loading = false;
  draft.success = false;
  draft.error = true;
};

export const defaultValue = (draft: actionDraftInterface) => {
  draft.loading = false;
  draft.success = false;
  draft.errorType = null;
};
